
vertex_index: u32 $VertexIndex;

out_position: f32v4 $VertexPosition;
out_color: f32v3 $Output(0); 

colors: [3]f32v3 = f32v3.[
    f32v3.(1.0, 0.0, 0.0),
    f32v3.(0.0, 1.0, 0.0),
    f32v3.(0.0, 0.0, 1.0)
];

positions: [3]f32v2 = f32v2.[
	f32v2.( 0.0, -0.5),
	f32v2.( 0.5,  0.5),
	f32v2.(-0.5,  0.5)
];

a: s32;
b: s32;
c: s32;
d: f32;

a = (
      (
         (a + (1->s32)) 
         * 
         (
           (b - (2->s32)) 
           / 
           ( (c->u32 + (b->u32)) -> s32 )
         )
      )
      -
      (
         (
           (a)->f32 
           - 
           ( (4->f32) + ((b + (f32v3.(1.0, 1.0, 1.0)*0.125).x->s32 + (5->s32))->f32) )
         )
         / 
         (
           (c)->f32 
           - 
           ( ((6->s32)->f32) * (d + (7->f32)) )
         )
      ) -> s32
    ) -> f32 -> s32
    *
    (
         ((a + (8->s32))->f32)
         - 
         (((b)->u32 - (c->u32))->f32)
         + 
         ((10->s32)->f32)
    ) -> s32;
    
b = a;

pos: f32v2 = positions[vertex_index];

out_position = f32v4.(pos.x, pos.y, 0.0, 1.0);
out_color = colors[vertex_index] * 0.85;


