
vertex_index: u32 $VertexIndex;

in_position: f32v4 $Input(0);
in_color: float3 $Input(1);
in_uv: f32v2 $Input(2);

//VS_Out :: struct {
//	color: f32v3;
//	uv: f32v2;
//	pos: f32v4;
//}

out_position: f32v4 $VertexPosition;
//fs_in: VS_Out $Output(0);
out_color: f32v3 $Output(0);
out_uv: f32v2 $Output(1);
out_pos: f32v4 $Output(2);
out_position = in_position;

//fs_in.color = in_color * 0.85;
//fs_in.uv = in_uv;
//fs_in.pos = out_position;
out_color = in_color * 0.85;
out_uv = in_uv;
out_pos = out_position;

