a: s32;
b: s32;
c: s32;
d: f32;

a = (
      (
         (a + (1->s32)) 
         * 
         (
           (b - (2->s32)) 
           / 
           ( (c->u32 + (b->u32)) -> s32 )
         )
      )
      -
      (
         (
           (a)->f32 
           - 
           ( (4->f32) + ((b + (f32v3.(1.0, 1.0, 1.0)*0.125).x->s32 + (5->s32))->f32) )
         )
         / 
         (
           (c)->f32 
           - 
           ( ((6->s32)->f32) * (d + (7->f32)) )
         )
      ) -> s32
    ) -> f32 -> s32
    *
    (
         ((a + (8->s32))->f32)
         - 
         (((b)->u32 - (c->u32))->f32)
         + 
         ((10->s32)->f32)
    ) -> s32;
    
b = a;


v4: f32v4;
bonkers: f32v2 = v4.xyz.yzz.zzx.yz.xy.yx.xx;

/*
#if STAGE_VERTEX {
	kernel_vs :: () {
		
	}
	kernel_vs();
} else if STAGE_FRAGMENT {
	kernel_fs :: () {
		
	}
	kernel_fs();
}
*/